# See config.example.yml for documentation.
name: yasikiE1
object_base: orig/GLMP01_1
object: sys/main.dol
hash: a1e2bd82813787cfe0b11afb5d138f08fdbd94f1
symbols: config/GLMP01_1/symbols.txt
splits: config/GLMP01_1/splits.txt
mw_comment_version: 8

quick_analysis: true
detect_objects: true
detect_strings: true

