# See config.example.yml for documentation.
object: orig/GLME01/sys/main.dol
hash: 77d49225e7d28b9777916cdbe5809345c570ecbc
symbols: config/GLME01/symbols.txt
splits: config/GLME01/splits.txt
mw_comment_version: 8

quick_analysis: true
detect_objects: true
detect_strings: true

