# See config.example.yml for documentation.
name: yasikiU1
object_base: orig/GLME01_1
object: sys/main.dol
hash: aa2bf3c958ec8170473808741bc1ea09ada85735
symbols: config/GLME01_1/symbols.txt
splits: config/GLME01_1/splits.txt
mw_comment_version: 8

quick_analysis: true
detect_objects: true
detect_strings: true

