# See config.example.yml for documentation.
name yasikiE2
object_base: orig/GLMP01_2
object: sys/main.dol
hash: c9099665a33be49b16caa5c216c7e1094276c032
symbols: config/GLMP01_2/symbols.txt
splits: config/GLMP01_2/splits.txt
mw_comment_version: 8

quick_analysis: false
detect_objects: true
detect_strings: true

