# See config.example.yml for documentation.
object_base: orig/GLMP01
object: sys/main.dol
hash: a1e2bd82813787cfe0b11afb5d138f08fdbd94f1
symbols: config/GLMP01/symbols.txt
splits: config/GLMP01/splits.txt
mw_comment_version: 8

quick_analysis: false
detect_objects: true
detect_strings: true

