name: yasiki
object_base: orig/GLMJ01
object: sys/main.dol
hash: 722005ea9c1eab54b114f814734d8f327e5614ee
symbols: config/GLMJ01/symbols.txt
splits: config/GLMJ01/splits.txt
mw_comment_version: 8

quick_analysis: true
detect_objects: true
detect_strings: true

extract:
- symbol: JUTResFONT_Sjsfont
  binary: system/FontData/Sjsfont.bfn
